FROM ubuntu:16.04
RUN apt-get update && apt-get install -y sudo && useradd -d /home/ubuntu -ms /bin/bash -g root -G sudo -p '' ubuntu
USER ubuntu
WORKDIR /home/ubuntu
RUN sudo apt-get install -y git \
    && sudo apt-get install -y curl \
    && sudo apt-get install -y build-essential libssl-dev \
    && curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh -o install_nvm.sh \
    && bash install_nvm.sh \
    && export NVM_DIR="$HOME/.nvm" \
    && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" \
    && [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" \
    && nvm install 8.12.0 \
    && nvm use 8.12.0