FROM ubuntu:16.04
RUN apt-get update && apt-get install -y sudo && useradd -d /home/ubuntu -ms /bin/bash -g root -G sudo -p '' ubuntu
USER ubuntu
WORKDIR /home/ubuntu
RUN sudo apt-get install -y git \
    && sudo apt-get install -y curl \
    && sudo apt-get install -y build-essential libssl-dev